# TV Arm Controller Configuration

# Hardware Configuration
hardware:
  # DC Motor GPIO pins for TB6612FNG driver (BCM numbering)
  # Motor A (X-axis)
  motor_x_ain1_pin: 17  # Pin 11 - Motor A direction 1
  motor_x_ain2_pin: 27  # Pin 13 - Motor A direction 2  
  motor_x_pwm_pin: 18   # Pin 12 - Motor A speed (PWM)
  
  # Motor B (Y-axis)
  motor_y_ain1_pin: 22  # Pin 15 - Motor B direction 1
  motor_y_ain2_pin: 23  # Pin 16 - Motor B direction 2
  motor_y_pwm_pin: 19   # Pin 35 - Motor B speed (PWM)
  
  # Shared standby pin (optional - set to null if not used)
  motor_stby_pin: 24    # Pin 18 - Standby (HIGH to enable motors)
  
  # ADS1115 ADC configuration
  ads1115:
    address: 0x48  # Default I2C address
    gain: 1        # ±4.096V range
    data_rate: 860 # Samples per second
  
  # Potentiometer channels on ADS1115
  potentiometer:
    x_axis_channel: 0  # A0 - X-axis position feedback
    y_axis_channel: 2  # A2 - Y-axis position feedback
  
  # DC Motor configuration
  dc_motor:
    frequency: 1000   # PWM frequency for speed control (Hz)
    min_position: 0   # Minimum position (%)
    max_position: 100 # Maximum position (%)
    default_speed: 80 # Default motor speed (%) - increased for better movement
    movement_timeout: 10  # Maximum time for movement (seconds)
    invert_x_direction: true   # X motor direction inverted - FORWARD extends, REVERSE retracts
    invert_y_direction: true   # Y motor direction inverted - FORWARD decreases, REVERSE increases
    use_closed_loop: true     # Use closed-loop control with position feedback
    position_tolerance: 1.0   # Position tolerance for closed-loop control (%) - reduced for precision
    max_move_time: 10.0       # Maximum time to reach target position (seconds)
    
  # Position limits and calibration
  calibration:
    x_axis:
      min_voltage: 0.8    # Minimum potentiometer voltage (based on your actual readings)
      max_voltage: 3.15   # Maximum potentiometer voltage (based on your 3.10V readings)
      min_position: 0     # Minimum position (%)
      max_position: 100   # Maximum position (%)
      max_drift_percent: 50.0  # Increased to accommodate voltage range changes
      enable_filtering: false  # Temporarily disable for closed-loop control testing
    y_axis:
      min_voltage: 0.1
      max_voltage: 3.2
      min_position: 0
      max_position: 100
      max_drift_percent: 50.0  # Increased to accommodate voltage range changes
      enable_filtering: false  # Temporarily disable for closed-loop control testing
  
  # Actual TV mount positions (calibrated)
  positions:
    wall:
      x: 97.0      # X position when physically at wall
      y: 23.0       # Y position when physically at wall
    extended:
      x: 62.4       # X position when physically extended
      y: 88.6       # Y position when physically extended

# Home Assistant Integration
home_assistant:
  mqtt:
    broker: "192.168.1.100"    # Your Home Assistant IP
    port: 1883
    username: "mqtt_user"       # Your MQTT username
    password: "mqtt_password"   # Your MQTT password
    client_id: "tv_arm_controller"
    
  # Device configuration for Home Assistant discovery
  device:
    name: "TV Arm Controller"
    identifier: "tv_arm_001"
    manufacturer: "DIY"
    model: "Pi Zero 2W TV Arm"
    sw_version: "1.0.0"
    
  # MQTT topics
  topics:
    base: "homeassistant/cover/tv_arm"
    command: "homeassistant/cover/tv_arm/set"
    state: "homeassistant/cover/tv_arm/state"
    position: "homeassistant/cover/tv_arm/position"
    x_position: "homeassistant/number/tv_arm_x/set"
    y_position: "homeassistant/number/tv_arm_y/set"
    x_state: "homeassistant/number/tv_arm_x/state"
    y_state: "homeassistant/number/tv_arm_y/state"

# System Configuration
system:
  # Logging configuration
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "/var/log/tv-arm-controller.log"
  
  # Control loop timing
  position_update_interval: 0.1  # seconds
  mqtt_publish_interval: 1.0     # seconds
  
  # Safety settings
  max_move_time: 30.0           # Maximum time for any movement (seconds)
  position_tolerance: 2.0       # Position tolerance (%)
  emergency_stop_enabled: true
  
  # Startup behavior
  restore_position_on_startup: true
  default_x_position: 50        # Default X position (%)
  default_y_position: 50        # Default Y position (%)

# Path Recording and Playback Configuration
path_recording:
  # Recording settings
  recording_interval: 0.1       # How often to record position (seconds)
  position_tolerance: 1.0       # Minimum position change to record (%)
  paths_directory: "recorded_paths"  # Directory to store recorded paths
  
  # Playback settings
  default_playback_speed: 1.0   # Default playback speed multiplier
  smooth_playback: true         # Enable smooth interpolation between points
  
  # Safety settings
  max_recording_duration: 300   # Maximum recording time (seconds)
  max_path_points: 10000        # Maximum points per recorded path
